# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "BMV"
  config.vm.provider "virtualbox" do |vb|
  end

  config.vm.network "forwarded_port", guest: 80, host: 8037, host_ip: "127.0.0.1"

  # config.vm.network "private_network", ip: "192.168.33.10"

  # config.vm.network "public_network"

  config.vm.synced_folder ".", "/usr/share/nginx/html"

  config.vm.provision "shell", path: "provision.sh"
end
